name: idm
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pip>=23.3.1

  - pip:
      - "huggingface_hub>=0.17,<0.20"
      - accelerate==0.25.0
      - torchmetrics==1.2.1
      - tqdm==4.66.1
      - transformers==4.36.2
      - diffusers==0.25.0
      - einops==0.7.0
      - bitsandbytes==0.39.0
      - scipy==1.11.1
      - opencv-python
      - gradio==4.24.0
      - fvcore
      - cloudpickle
      - omegaconf
      - pycocotools
      - basicsr
      - av
      - onnxruntime==1.16.2
